argo-cd:
  global:
    domain: ""
  server:
    service:
      type: ClusterIP 
    extraArgs:
      - --insecure
    metrics:
      enabled: true
      service:
        type: ClusterIP
        servicePort: 8084
        portName: http-metrics
      serviceMonitor:
        enabled: true
        interval: 30s
        selector: {}
        additionalLabels: 
          release: "prometheus"
        namespace: "monitoring"
        annotations: {}
  
    ingress:
      enabled: true
      hostname: ""
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      ingressClassName: nginx
      path: /argocd(/|$)(.*)
      pathType: ImplementationSpecific
        
  configs:
    params:
      server.insecure: "true"
      server.basehref: "/argocd"











