apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-sharks
  annotations:
    nginx.ingress.kubernetes.io/priority: "1"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  -  http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sharks-service
            port:
              number: 80










