apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-sharks
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  -  http:
      paths:
      - pathType: Prefix
        path: "/health"
        backend:
          service:
            name: sharks-service
            port:
              number: 80
      - pathType: Exact
        path: "/sharks"
        backend:
          service:
            name: sharks-service
            port:
              number: 80





