apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  project: default
  source:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 76.3.0
      helm:
        valueFiles:
          - $eks_setup/k8s_manifests/third-party/monitoring/base/values.yaml  
        parameters:
        - name: "prometheusOperator.crds.enabled"
          value: "true"
        skipCrds: true

    - repoURL: https://github.com/adebisea/eks_setup
      targetRevision: main
      ref: eks_setup 
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true


