name: Bootstrap cluster

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/boostrap-cluster.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/boostrap-cluster.yaml'
  workflow_dispatch: 

env:
  REGION: ${{ vars.REGION }}
  CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
  

jobs:
  bootstrap:
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'Merge pull request')
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: k8s_manifests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: k8s_manifests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Setup kubeconfig
        run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.REGION }}

      - name: Setup docker secret
        run: |
          kubectl create namespace sharks 
          kubectl create secret docker-registry ghcr-secret -n sharks  --docker-server=https://ghcr.io  --docker-username=${{ github.repository_owner }} --docker-password=${{ secrets.SECRET_PASSWORD }}

      - name: Install Argo CD (Helm)
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm upgrade --install argocd argo/argo-cd -n argocd --create-namespace -f third-party/argocd/helm-install/values.yaml

      - name: Apply App of Apps
        run: |
          kubectl apply -f root-argocd-app.yaml -n argocd
          
      - name: Get AWS Account ID
        run: |
          echo "ACCOUNTID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV
          
      - name: Install lbc eks (Helm)
        run: |
          helm repo add eks https://aws.github.io/eks-charts
          helm repo update eks
          helm install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=${{ env.CLUSTER_NAME }} --set region=${{ env.REGION }} --set serviceAccount.create=true --set serviceAccount.name=aws-load-balancer-controller --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=arn:aws:iam::${{ env.ACCOUNTID }}:role/load-balancer-controller-irsa --version 1.14.0
      
      - name: Install ebs csi (eks addon)
        run: |
          aws eks create-addon   --cluster-name ${{ env.CLUSTER_NAME }}   --addon-name aws-ebs-csi-driver   --service-account-role-arn arn:aws:iam::${{ env.ACCOUNTID }}:role/EKS_EBS_CSI_DriverRole --region ${{ env.REGION }}



















