controller:
  service:
    type: LoadBalancer
  admissionWebhooks:
    enabled: true
    patch:
      enabled: true
      image:
        registry: registry.k8s.io
        image: ingress-nginx/kube-webhook-certgen
        tag: v1.5.0 

  metrics:
    port: 10254
    portName: metrics
  # if this port is changed, change healthz-port: in extraArgs: accordingly
    enabled: false
    service:
      # -- Enable the metrics service or not.
      enabled: true
      prometheus.io/scrape: "true"
  
      prometheus.io/port: "10254"




